/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mojPackage;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmet
 */
public class GlavniProzor extends javax.swing.JFrame {

    /**
     * Creates new form GlavniProzor
     */
    public GlavniProzor() {
        initComponents();

        // prozor bude full-screen
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        poljeZaUnos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        dugmeZaKod = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kodiraniSimboli = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        dekodiraniTekst = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        kodiraniTekst = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Hafmanovo kodiranje");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        poljeZaUnos.setColumns(20);
        poljeZaUnos.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        poljeZaUnos.setLineWrap(true);
        poljeZaUnos.setRows(5);
        jScrollPane1.setViewportView(poljeZaUnos);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Unesite tekst:");

        dugmeZaKod.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dugmeZaKod.setText("Kodirajte tekst");
        dugmeZaKod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dugmeZaKodMouseClicked(evt);
            }
        });

        kodiraniSimboli.setEditable(false);
        kodiraniSimboli.setColumns(20);
        kodiraniSimboli.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        kodiraniSimboli.setLineWrap(true);
        kodiraniSimboli.setRows(5);
        jScrollPane2.setViewportView(kodiraniSimboli);

        dekodiraniTekst.setEditable(false);
        dekodiraniTekst.setColumns(20);
        dekodiraniTekst.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        dekodiraniTekst.setLineWrap(true);
        dekodiraniTekst.setRows(5);
        jScrollPane3.setViewportView(dekodiraniTekst);

        kodiraniTekst.setEditable(false);
        kodiraniTekst.setColumns(20);
        kodiraniTekst.setFont(new java.awt.Font("DialogInput", 2, 18)); // NOI18N
        kodiraniTekst.setLineWrap(true);
        kodiraniTekst.setRows(5);
        jScrollPane4.setViewportView(kodiraniTekst);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Kodirani simboli:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Dekodirani tekst:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Kodirani tekst:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                                .addComponent(dugmeZaKod, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dugmeZaKod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dugmeZaKodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dugmeZaKodMouseClicked
        // TODO add your handling code here:
        // postavljam da su textboxovi prazni
        kodiraniSimboli.setText("");
        kodiraniTekst.setText("");
        dekodiraniTekst.setText("");

        /* 
        racunam koliko simbola ima, ako ima samo jedan simbol prijavljujem 
        error korisniku da mora imati bar dva simbolja
         */
        Map<Character, Integer> frekvencijeZnaka = new HashMap<>();

        for (char znak : poljeZaUnos.getText().toCharArray()) {
            frekvencijeZnaka.put(znak, frekvencijeZnaka.getOrDefault(znak, 0) + 1);
        }
        if (frekvencijeZnaka.size() == 1) {
            JOptionPane.showMessageDialog(null, "Poruka mora imati više od jednog simbola!");
        } else {
            // poziva se klasa za generisanje huffmanovog koda na osnovu unetog teksta
            Object[] rezultatKodiranja = HafmanovoKodiranje.generisatiHuffmanStablo(poljeZaUnos.getText());

            kodiraniSimboli.setText("Kodirani simboli su: " + rezultatKodiranja[0]);
            kodiraniTekst.setText("Kodirani tekst je: " + rezultatKodiranja[1]);
            dekodiraniTekst.setText("Dekodirani tekst je: " + rezultatKodiranja[2]);
        }
    }//GEN-LAST:event_dugmeZaKodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavniProzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dekodiraniTekst;
    private javax.swing.JButton dugmeZaKod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea kodiraniSimboli;
    private javax.swing.JTextArea kodiraniTekst;
    private javax.swing.JTextArea poljeZaUnos;
    // End of variables declaration//GEN-END:variables
}
